version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-docker:
        patterns:
        - "docker/*"
        - "peter-evans/dockerhub-description"
      actions-patch:
        patterns:
        - "*"
        update-types:
        - "patch"
