name: Update PHP

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: wget -O version.json "https://www.php.net/releases/index.php?json&version=8.1"
      - name: Get latest version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'version.json'
            prop_path: 'version'
      - run: sed -i 's/PHP.*Composer/PHP ${{steps.version.outputs.prop}} + Composer/g' README.md
      - run: rm version.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.3
        with:
            token: ${{ secrets.PAT }}
            commit-message: 'PHP ${{steps.version.outputs.prop}}'
            committer: 'Nikolas Evers <vintagesucks@users.noreply.github.com>'
            branch: 'php-${{steps.version.outputs.prop}}'
            delete-branch: true
            title: 'PHP ${{steps.version.outputs.prop}}'
            body: 'This pull request was [created automatically](https://github.com/vintagesucks/docker-jammy-node18-chrome-php8.1/blob/main/.github/workflows/update-php.yml). Please check if ${{steps.version.outputs.prop}} is [available at the PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php8.1&field.status_filter=published&field.series_filter=jammy) before merging.'
