name: Update PHP

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: wget -O version.json "https://api.launchpad.net/devel/~ondrej/+archive/ubuntu/php?ws.op=getPublishedSources&exact_match=true&source_name=php8.1&status=Published&distro_series=https://api.launchpad.net/devel/ubuntu/jammy"
      - name: Get latest version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'version.json'
            prop_path: 'entries.0.source_package_version'
      - id: php
        run: 'echo "version=$(echo "${{ steps.version.outputs.prop }}" | cut -d- -f1)" >> "$GITHUB_OUTPUT"'
      - run: sed -i "s/PHP.*Composer/PHP ${{ steps.php.outputs.version }} + Composer/g" README.md
      - run: rm version.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.6
        with:
            token: ${{ secrets.PAT }}
            commit-message: 'PHP ${{steps.php.outputs.version}}'
            committer: 'Nikolas Evers <vintagesucks@users.noreply.github.com>'
            branch: 'php-${{steps.php.outputs.version}}'
            delete-branch: true
            title: 'PHP ${{steps.php.outputs.version}}'
            body: 'This pull request was [created automatically](https://github.com/vintagesucks/docker-jammy-node18-chrome-php8.1/blob/main/.github/workflows/update-php.yml).'
